services:
  # ==========================================
  # Base de datos MySQL
  # ==========================================
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # ==========================================
  # Servidor gRPC (Spring Boot)
  # ==========================================
  grpc-server:
    build:
      context: ../TP-Distribuidos-GrupoC-backend/grpc_server
    image: sd-grpc-server-grupo-c:1.0
    container_name: grpc-server
    restart: always
    ports:
      - "9090:9090"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      MAILHOG_URL: ${MAILHOG_URL}
    depends_on:
      - mysql
  
  # ==========================================
  # MailHog
  # ==========================================
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"  # puerto SMTP
      - "8025:8025"  # interfaz web

  # ==========================================
  # Cliente gRPC (Express)
  # ==========================================
  grpc-client:
    build:
      context: ../TP-Distribuidos-GrupoC-backend/grpc_client
    image: sd-grpc-client-grupo-c:1.0
    container_name: grpc-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      GRPC_SERVER_URL: ${GRPC_SERVER_URL}
    depends_on:
      - grpc-server

  # ==========================================
  # Frontend React
  # ==========================================
  frontend:
    build:
      context: ../TP-Distribuidos-GrupoC-frontend
    image: sd-frontend-grupo-c:1.0
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - grpc-client

volumes:
  db_data: